apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terminal.fullname" . }}
  labels:
    {{- include "terminal.labels" . | nindent 4 }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      {{- include "terminal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "terminal.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      enableServiceLinks: {{ .Values.podEnableServiceLinks}}
      automountServiceAccountToken: {{ .Values.podAutomountServiceAccountToken}}
      serviceAccountName: {{ include "terminal.serviceAccountName" . }}
      hostname: {{ .Values.hostname }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: NTTY
            value: "5"
          ports:
            - name: http
              containerPort: 7681
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
