{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "terminal.serviceAccountName" . }}
  labels:
{{ include "terminal.labels" . | nindent 4 }}
{{- end -}}
